# Generated by Django 2.2.9 on 2020-08-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Jobseeker', 'Jobseeker'), ('Company', 'Company'), ('Admin', 'Admin')], default='Jobseeker', max_length=50),
        ),
    ]
