# Generated by Django 2.2.9 on 2020-08-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Jobseeker', 'Jobseeker'), ('Company', 'Company'), ('Admin', 'Admin')], max_length=50),
        ),
    ]
