# Generated by Django 2.2.9 on 2020-03-18 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('telephone', models.CharField(max_length=12)),
                ('emial', models.EmailField(max_length=254)),
                ('skype_name', models.CharField(max_length=50)),
                ('website', models.URLField()),
                ('date_start', models.DateField()),
                ('working_hour', models.CharField(max_length=30)),
                ('working_day', models.CharField(max_length=30)),
                ('no_of_emp', models.IntegerField()),
                ('xcoord', models.FloatField()),
                ('ycoord', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='jobdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('publish_on', models.DateField()),
                ('expired_on', models.DateField()),
                ('experience', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('job_type', models.CharField(choices=[('Part Time', 'Part Time'), ('Full Time', 'Full Time'), ('Intership', 'Intership')], default='Full Time', max_length=30)),
                ('description', models.TextField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='jobapi.company')),
            ],
        ),
        migrations.CreateModel(
            name='jobskill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobskill', to='jobapi.jobdetail')),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='jobapi.company')),
            ],
        ),
        migrations.CreateModel(
            name='company_depart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_depart', to='jobapi.company')),
            ],
        ),
        migrations.CreateModel(
            name='company_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_addr', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='jobapi.company')),
            ],
        ),
    ]
