# Generated by Django 2.2.9 on 2020-07-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='xcoord',
        ),
        migrations.RemoveField(
            model_name='company',
            name='ycoord',
        ),
        migrations.AddField(
            model_name='company_address',
            name='xcoord',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='company_address',
            name='ycoord',
            field=models.FloatField(null=True),
        ),
    ]
