# Generated by Django 2.2.9 on 2020-03-18 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobseeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=13)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=50)),
                ('date_of_brith', models.DateField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('job_type', models.CharField(choices=[('Permanent', 'Permanent'), ('Temporry/Contract', 'Temporry/Contract'), ('Both', 'Both')], default='Both', max_length=50)),
                ('employment_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Both', 'Both')], default='Both', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50)),
                ('jobseeker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='usersapi.Jobseeker')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.FileField(upload_to='Resume')),
                ('profile', models.ImageField(blank=True, null=True, upload_to='Image')),
                ('jobseeker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='usersapi.Jobseeker')),
            ],
        ),
        migrations.CreateModel(
            name='Higher_Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(choices=[('Doctorate/Ph.D', 'Doctorate/Ph.D'), ('Masters/Post-Graduation', 'Masters/Post-Graduation'), ('Graduation/Diploma', 'Graduation/Diploma')], max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=50)),
                ('university_college', models.CharField(max_length=150)),
                ('course_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Correspondence', 'Correspondence')], default='Full Time', max_length=50)),
                ('passing_year', models.CharField(max_length=4)),
                ('jobseeker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_education', to='usersapi.Jobseeker')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(choices=[('12th', '12th'), ('10th', '10th'), ('Below 10th', 'Below 10th')], max_length=50)),
                ('Board', models.CharField(max_length=50)),
                ('yerar_of_passing', models.CharField(max_length=4)),
                ('medium', models.CharField(max_length=50)),
                ('percentage', models.CharField(max_length=50)),
                ('jobseeker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='usersapi.Jobseeker')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_addr', models.TextField()),
                ('local_area_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('jobseeker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='usersapi.Jobseeker')),
            ],
        ),
    ]
