# Generated by Django 2.2.9 on 2020-07-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapi', '0002_jobseeker_experians'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='xcoord',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='ycoord',
            field=models.FloatField(null=True),
        ),
    ]
