# Generated by Django 2.2.9 on 2020-08-11 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersapi', '0003_auto_20200723_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='owner',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
