# Generated by Django 2.2.9 on 2020-08-11 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersapi', '0004_jobseeker_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='owner',
        ),
    ]
